package org.hibernate.odm.jdbc

import com.mongodb.client.MongoClient
import com.mongodb.client.MongoDatabase
import java.sql.Blob
import java.sql.CallableStatement
import java.sql.Clob
import java.sql.DatabaseMetaData
import java.sql.NClob
import java.sql.PreparedStatement
import java.sql.SQLWarning
import java.sql.SQLXML
import java.sql.Statement
import java.sql.Struct

internal class MongoConnection(client: MongoClient) : AbstractCloseable(), ConnectionAdapter {
    private val clientSession = client.startSession()

    override fun closeActually() {
        clientSession.close()
    }

    override fun createStatement(): Statement {
        ensureNotClosed()
        TODO()
    }

    override fun prepareStatement(sql: String): PreparedStatement {
        ensureNotClosed()
        TODO()
    }

    override fun prepareCall(sql: String): CallableStatement {
        ensureNotClosed()
        TODO("MongoDB has no SQL stored procedure counterpart")
    }

    override fun setAutoCommit(autoCommit: Boolean) {
        ensureNotClosed()
        TODO()
    }

    override fun getAutoCommit(): Boolean {
        ensureNotClosed()
        TODO()
    }

    override fun commit() {
        ensureNotClosed()
        TODO()
    }

    override fun rollback() {
        ensureNotClosed()
        TODO()
    }

    override fun getMetaData(): DatabaseMetaData {
        ensureNotClosed()
        TODO()
    }

    override fun setTransactionIsolation(level: Int) {
        ensureNotClosed()
        TODO("MongoDB has no SQL transaction isolation level counterpart")
    }

    override fun getTransactionIsolation(): Int {
        ensureNotClosed()
        TODO("MongoDB has no SQL transaction isolation level counterpart")
    }

    override fun getWarnings(): SQLWarning? {
        ensureNotClosed()
        TODO()
    }

    override fun clearWarnings() {
        ensureNotClosed()
        TODO()
    }

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int
    ): PreparedStatement {
        ensureNotClosed()
        TODO()
    }

    override fun prepareCall(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int
    ): CallableStatement {
        ensureNotClosed()
        TODO("MongoDB has no SQL stored procedure counterpart")
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        ensureNotClosed()
        TODO()
    }

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement {
        ensureNotClosed()
        TODO()
    }

    override fun createClob(): Clob {
        ensureNotClosed()
        TODO()
    }

    override fun createBlob(): Blob {
        ensureNotClosed()
        TODO()
    }

    override fun createNClob(): NClob {
        ensureNotClosed()
        TODO()
    }

    override fun createSQLXML(): SQLXML {
        ensureNotClosed()
        TODO()
    }

    override fun createArrayOf(typeName: String, elements: Array<out Any>): java.sql.Array {
        ensureNotClosed()
        TODO()
    }

    override fun createStruct(typeName: String, attributes: Array<out Any>): Struct {
        ensureNotClosed()
        TODO()
    }
}
