name: Integration Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [ '6.0', '7.0', '8.0' ]
    steps:
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
    - uses: gradle/actions/setup-gradle@v4
    - run: ./gradlew integrationTest
